## Fix route ruta directa

Este notebook limpia las rutsa de ruta directa, pasa a ser lineas sobrelapeadas a una sola linea por ruta sin sobrelape

![rutas](assets/depic_cambio.png)

In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
path_gtfs = "../1-scraping_ruta_directa/data/proc/rutas_procesadas_tampico_1.geojson"

In [3]:
routes = gpd.read_file(path_gtfs)
routes.head()

,data.route.shortName,data.route.longName,shape_id,geometry
0,74,Isleta Pérez,shape_74,"LINESTRING (-97.84481 22.20913, -97.84525 22.2..."
1,76,Cascajal,shape_76,"LINESTRING (-97.87153 22.22684, -97.87129 22.2..."
2,81,Golfo,shape_81,"LINESTRING (-97.83941 22.22638, -97.84048 22.2..."
3,89A,Altamira - Tampiquito por Soriana,shape_89A,"LINESTRING (-97.92128 22.41213, -97.92228 22.4..."
4,67,Central Camionera - Madero,shape_67,"LINESTRING (-97.85804 22.25045, -97.85752 22.2..."

## Calcular longitud

In [4]:
import geopandas as gpd

# 1️⃣ Asegúrate del CRS actual
print(routes.crs)
# Si dice EPSG:4326 (lat/lon), proyecta a UTM (para México, por ejemplo zona 14N)
routes_m = routes.to_crs(32614)

# 2️⃣ Calcula la longitud (en metros)
routes_m["length_m"] = routes_m.length

# 3️⃣ (Opcional) también en kilómetros
routes_m["length_km"] = routes_m["length_m"] / 1000

# 4️⃣ Muestra resultado
routes_m = routes_m.sort_values("length_m", ascending=False).reset_index(drop=True)
routes_m.head(40)

EPSG:4326

,data.route.shortName,data.route.longName,shape_id,geometry,length_m,length_km
0,108,Cuauhtémoc - Tampico - Universidad Politécnica...,shape_108,"LINESTRING (586676.687 2493248.966, 587405.453...",114364.339311,114.364339
1,108A,Cuauhtémoc - Tampico - Univ. Politécnica de Al...,shape_108A,"LINESTRING (586674.631 2493248.954, 587420.891...",113857.569719,113.857570
2,111A,Tampico - Colonias - El Fuerte - Penal por Av....,shape_111A,"LINESTRING (595215.577 2481185.929, 595276.649...",101312.989576,101.312990
3,114,López Mateos - Margaritas - Tampico por Av. Hi...,shape_114,"LINESTRING (595812.56 2493252.291, 595203.134 ...",99403.236689,99.403237
4,11,Tampico - Colonias - El Fuerte - Penal por Av....,shape_11,"LINESTRING (595215.577 2481185.929, 595276.649...",99266.776666,99.266777
5,114A,López Mateos - Margaritas - Tampico por Ayunta...,shape_114A,"LINESTRING (595812.56 2493252.291, 595203.134 ...",98834.685863,98.834686
6,36,Santa Amalia - Polvorín - Madero -,shape_36,"LINESTRING (617669.347 2456914.141, 617937.312...",88190.919554,88.190920
7,107,Santa Amalia - Tampico por Av. Hidalgo y Ayunt...,shape_107,"LINESTRING (605690.245 2479892.31, 605911.353 ...",66869.299309,66.869299
8,103B,Electricistas - Arboledas - Tampico por H. Ayu...,shape_103B,"LINESTRING (609746.409 2479210.919, 609615.563...",66000.758629,66.000759
9,107A,Santa Amalia - Tampico por Ayuntamiento y Av....,shape_107A,"LINESTRING (605690.245 2479892.31, 605911.353 ...",64805.005254,64.805005
10,106A,Puerto Industrial - Tampico por Av. Hidalgo y ...,shape_106A,"LINESTRING (614762.785 2482636.258, 613554.55 ...",64255.532723,64.255533
11,106,Puerto Industrial - Tampico por Av. Hidalgo y ...,shape_106,"LINESTRING (614762.785 2482636.258, 613554.55 ...",63425.417612,63.425418
12,100A,Infonavit - Altamira - Tampico por Av. Ayuntam...,shape_100A,"LINESTRING (608045.004 2476689.138, 608322.139...",59709.498317,59.709498
13,100,Infonavit - Altamira - Tampico por Av. Hidalgo...,shape_100,"LINESTRING (608047.063 2476689.152, 608321.086...",59653.096158,59.653096
14,103,Pedrera - Arboledas - Tampico por Av. Hidalgo ...,shape_103,"LINESTRING (615442.083 2475733.942, 615464.062...",57100.988115,57.100988
15,109,Aldama - Lomas del Real - Tampico por Ayuntami...,shape_109,"LINESTRING (613884.423 2481448.449, 614628.551...",56005.146784,56.005147
16,103A,Pedrera - Arboledas - Tampico por Av. Hidalgo ...,shape_103A,"LINESTRING (615442.083 2475733.942, 615464.062...",55939.704131,55.939704
17,109A,Aldama - Lomas del Real - Tampico por Av. Hida...,shape_109A,"LINESTRING (613884.423 2481448.449, 614628.551...",55152.338492,55.152338
18,53,Altamira,shape_53,"LINESTRING (608964.266 2479187.674, 609388.727...",54035.818849,54.035819
19,110,Universidad Politécnica de Altamira - Santa Am...,shape_110,"LINESTRING (606326.543 2482705.386, 606295.762...",53733.187228,53.733187
20,105,Zapata - Haciendas - Tampico por Av. Hidalgo y...,shape_105,"LINESTRING (616132.776 2473696.458, 616126.324...",50416.049130,50.416049
21,105,Zapata - Haciendas - Tampico por Av. Hidalgo y...,shape_105,"LINESTRING (616132.776 2473696.458, 616126.324...",50416.049130,50.416049
22,105,Zapata - Haciendas - Tampico por Av. Hidalgo y...,shape_105,"LINESTRING (616132.776 2473696.458, 616126.324...",50416.049130,50.416049
23,105,Zapata - Haciendas - Tampico por Av. Hidalgo y...,shape_105,"LINESTRING (616132.776 2473696.458, 616126.324...",50416.049130,50.416049
24,105A,Zapata - Haciendas - Tampico por Ayuntamiento ...,shape_105A,"LINESTRING (616132.776 2473696.458, 616126.324...",49352.470423,49.352470
25,104,Lomas de Altamira - Tampico por Av. Hidalgo y ...,shape_104,"LINESTRING (612253.757 2473127.613, 612199.242...",49117.724395,49.117724
26,9,Santa Elena - Colonias - Tampico,shape_9,"LINESTRING (618703.105 2469648.325, 618782.266...",46477.036406,46.477036
27,101A,Nuevo Madero - Tampico por Ayuntamiento y Av. ...,shape_101A,"LINESTRING (618574.03 2471578.174, 618607.529 ...",46359.906079,46.359906
28,54,Col Nuevo Tampico - Altamira por Carnitas Ortas,shape_54,"LINESTRING (608968.344 2479193.238, 609306.786...",46102.626214,46.102626
29,101,Nuevo Madero - Tampico por Av. Hidalgo y Ayunt...,shape_101,"LINESTRING (618571.97 2471578.158, 618607.554 ...",45664.226115,45.664226
30,16,Ejido Contadero - Germinal - Águila,shape_16,"LINESTRING (618773.504 2469736.326, 618788.279...",45519.781956,45.519782
31,19,Nuevo Madero - Serapio Venegas,shape_19,"LINESTRING (618385.89 2471804.806, 618366.855 ...",45298.936232,45.298936
32,4,Colosio - Águila Madero - Golfo,shape_4,"LINESTRING (613305.943 2469210.556, 613305.523...",44973.208604,44.973209
33,113,Univ. Politécnica de Altamira - Santa Amalia -...,shape_113,"LINESTRING (606335.835 2482701.022, 606228.655...",42921.981402,42.921981
34,5,Madero - Blanco Palmas - Albañiles,shape_5,"LINESTRING (617372.844 2469169.9, 617414.738 2...",42158.605453,42.158605
35,23,E. Cárdenas González - Universidad,shape_23,"LINESTRING (617498.93 2469114.39, 617574.506 2...",41878.065846,41.878066
36,45,E. C. González por Av. Hidalgo,shape_45,"LINESTRING (619719.202 2465571.919, 619670.653...",41036.404472,41.036404
37,115,Altamira - Zapata por Arboledas,shape_115,"LINESTRING (609757.558 2476768.719, 609791.162...",40570.660413,40.570660
38,42,Pedro José Méndez - Carnitas Orta,shape_42,"LINESTRING (614386.167 2467989.579, 614368.082...",40409.615852,40.409616
39,51,Serapio Venegas por Boulevard,shape_51,"LINESTRING (617675.954 2470356.818, 617005.316...",39799.203708,39.799204

## Guardar en archivos separados

In [6]:
import geopandas as gpd
import os

# Asegúrate de tener tu GeoDataFrame cargado
# routes = gpd.read_file("rutas.shp")  # o como sea que lo obtuviste

# Crea una carpeta de salida
output_folder = "./data/routes/rutas_individuales"
os.makedirs(output_folder, exist_ok=True)

# Itera por cada fila y guarda en un archivo distinto
for idx, row in routes.iterrows():
    shape_id = row["shape_id"]
    ruta = gpd.GeoDataFrame([row], columns=routes.columns, crs=routes.crs)

    # Archivo GeoJSON (puedes cambiar a .shp o .gpkg)
    output_path = os.path.join(output_folder, f"{shape_id}.geojson")
    ruta.to_file(output_path, driver="GeoJSON")

    print(f"✅ Guardado: {output_path}")
    
    import geopandas as gpd
import os

# Carpeta donde estaban los archivos originales
input_folder = "./data/routes/rutas_individuales"
# Carpeta para los archivos vacíos
output_folder = "./data/routes/rutas_vacias"
os.makedirs(output_folder, exist_ok=True)

# Recorre los nombres de los archivos existentes
for filename in os.listdir(input_folder):
    print(input_folder)
    if filename.endswith(".geojson"):
        shape_id = os.path.splitext(filename)[0]  # quita la extensión

        # Crear GeoDataFrame vacío con misma estructura
        empty_gdf = gpd.GeoDataFrame(columns=["data.route.shortName", "data.route.longName", "shape_id", "geometry"],
                                     geometry="geometry", crs="EPSG:4326")

        # Guardar el archivo vacío con el mismo nombre
        output_path = os.path.join(output_folder, f"{shape_id}.geojson")
        empty_gdf.to_file(output_path, driver="GeoJSON")

        print(f"🕳️ Archivo vacío generado: {output_path}")

✅ Guardado: ./data/routes/rutas_individuales/shape_74.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_76.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_81.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_89A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_67.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_82.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_66.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_75.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_59.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_56.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_73.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_85.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_71.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_69.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_72.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_88.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_61.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_77.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_65.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_64.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_62.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_112.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_68.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_60.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_84.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_88A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_87.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_89.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_32.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_58.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_63.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_12.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_27.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_80.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_8.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_117.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_86.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_44.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_83.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_70.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_79.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_118.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_21.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_17.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_20.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_28.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_14.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_43.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_46.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_29.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_Fracc..geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_41.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_34.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_49.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_15.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_78.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_6.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_3.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_39.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_48.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_22.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_33.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_52.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_120.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_30.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_57.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_18.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_25.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_7.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_55.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_119.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_116.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_37.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_47.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_24.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_40.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_31.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_1.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_2.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_50.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_90.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_38.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_10.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_26.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_51.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_42.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_115.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_45.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_23.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_5.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_113.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_4.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_19.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_16.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_101.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_54.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_101A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_9.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_104.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_105A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_105.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_105.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_105.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_105.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_110.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_53.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_109A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_103A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_109.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_103.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_100.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_100A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_106.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_106A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_107A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_103B.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_107.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_36.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_114A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_11.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_114.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_111A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_108A.geojson
✅ Guardado: ./data/routes/rutas_individuales/shape_108.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_88.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_31.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_21.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_53.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_43.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_105A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_8.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_106.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_116.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_Fracc..geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_120.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_81.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_28.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_38.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_75.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_65.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_17.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_1.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_39.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_29.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_80.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_90.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_64.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_74.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_16.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_20.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_30.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_89.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_103B.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_42.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_52.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_9.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_117.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_107.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_114A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_82.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_49.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_59.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_2.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_14.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_76.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_66.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_50.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_40.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_32.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_22.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_105.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_115.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_41.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_51.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_103A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_23.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_33.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_114.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_104.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_83.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_108A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_109A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_58.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_48.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_15.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_3.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_67.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_77.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_10.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_6.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_118.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_108.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_72.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_62.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_86.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_88A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_89A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_101.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_111A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_19.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_54.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_44.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_36.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_26.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_110.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_100.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_18.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_45.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_55.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_27.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_37.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_7.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_11.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_63.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_73.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_109.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_119.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_106A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_107A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_87.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_68.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_78.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_112.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_25.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_57.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_47.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_71.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_61.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_101A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_100A.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_5.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_85.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_60.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_70.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_12.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_4.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_84.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_113.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_103.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_79.geojson
./data/routes/rutas_individuales
🕳️ Archivo vacío generado: ./data/routes/rutas_vacias/shape_69.geojson
./data/routes/rutas_individuales

,data.route.shortName,data.route.longName,shape_id,geometry,length_m,length_km
53,119,Pedrera - Soriana - Aeropuerto,shape_119,"LINESTRING (615436.96 2475730.583, 615465.083 ...",33696.444991,33.696445

In [68]:
routes_select = routes_m.iloc[1:2,:]
routes_select.head()

,data.route.shortName,data.route.longName,shape_id,geometry,length_m,length_km
1,108A,Cuauhtémoc - Tampico - Univ. Politécnica de Al...,shape_108A,"LINESTRING (586674.631 2493248.954, 587420.891...",113857.569719,113.85757

In [76]:
routes_select = routes_m[routes_m["data.route.shortName"] == "119"]

In [77]:


# 3) Revisa las razones de fallo
print(res["reason"].value_counts(dropna=False).head(10))
print(res[res["reason"].notna()].head(10)[["reason"]])

# 4) Si ahora hay válidas:
centerlines = centerlines_ok
print(centerlines.head())

NameError: name 'res' is not defined

In [78]:
import geopandas as gpd
from shapely.geometry import LineString
from shapely.ops import linemerge

# Suponiendo que ya tienes:
# routes = routes.head(1)

# 1) Tomar la geometría y garantizar que sea un LineString
geom = routes_select.geometry.iloc[0]
if geom.geom_type == "MultiLineString":
    m = linemerge(geom)
    # si sigue siendo Multi, usa el tramo más largo
    if m.geom_type == "MultiLineString":
        geom = max(list(m.geoms), key=lambda g: g.length)
    else:
        geom = m

assert geom.geom_type == "LineString", "La geometría debe ser LineString o convertible a LineString."

# 2) Elegir n (número de segmentos)
n = 50  # <-- cámbialo a lo que necesites

# 3) Interpolar puntos y construir segmentos
pts = [geom.interpolate(geom.length * i / n) for i in range(n + 1)]
segs = [LineString([pts[i], pts[i+1]]) for i in range(n)]

# 4) Crear GeoDataFrame con 'order' y copiar atributos originales
row = routes_select.iloc[0].drop(labels=["geometry"])
seg_gdf = gpd.GeoDataFrame(
    [row.to_dict() for _ in range(n)],  # duplica atributos
    geometry=segs,
    crs=routes_select.crs
)
seg_gdf["order"] = range(1, n + 1)

# 5) (Opcional) guardar
seg_gdf.to_file(f"{routes_select.iloc[0]['shape_id']}_segments.geojson", driver="GeoJSON")

seg_gdf.head()

,data.route.shortName,data.route.longName,shape_id,length_m,length_km,geometry,order
0,119,Pedrera - Soriana - Aeropuerto,shape_119,33696.444991,33.696445,"LINESTRING (615436.96 2475730.583, 615029.639 ...",1
1,119,Pedrera - Soriana - Aeropuerto,shape_119,33696.444991,33.696445,"LINESTRING (615029.639 2476023.081, 614800.094...",2
2,119,Pedrera - Soriana - Aeropuerto,shape_119,33696.444991,33.696445,"LINESTRING (614800.094 2476548.826, 614744.118...",3
3,119,Pedrera - Soriana - Aeropuerto,shape_119,33696.444991,33.696445,"LINESTRING (614744.118 2477064.113, 614071.154...",4
4,119,Pedrera - Soriana - Aeropuerto,shape_119,33696.444991,33.696445,"LINESTRING (614071.154 2477028.058, 613745.363...",5

### Hacer buffer

| Región                  | EPSG (UTM) |
|--------------------------|-------------|
| Occidente (Guadalajara) | 32613       |
| Centro (CDMX, Puebla)   | 32614       |
| Oriente (Veracruz)      | 32615       |

In [80]:
seg_gdf = seg_gdf.to_crs(epsg=32615) 
#seg_gdf["geometry"] = seg_gdf["geometry"].buffer(5)
seg_gdf.to_file(f"./temp_segments_buffered.geojson", driver="GeoJSON") 
seg_gdf.explore(column="order")

### obtener linea a partir de buffer