## Codigo para analizar utas y paradas de  GTFS

In [18]:
import pandas as pd
import geopandas as gpd
import geopandas as gpd
from shapely.geometry import LineString

In [19]:
route = "7"

In [20]:
path_gtfs = "./data-gtfs/"

### Routes

In [ ]:
path_routes = path_gtfs + "shapes.txt"
routes = pd.read_csv(path_routes)

In [ ]:
routes = routes[routes["shape_id"]== f"shape_{route}-1"]
routes.head()

       shape_id  shape_pt_sequence  shape_pt_lon  shape_pt_lat
4655  shape_7-1                  0     -97.85320      22.21717
4656  shape_7-1                  1     -97.85240      22.21679
4657  shape_7-1                  2     -97.85492      22.21224
4658  shape_7-1                  3     -97.85587      22.21246
4659  shape_7-1                  4     -97.85326      22.21725

In [24]:
# 1. Ordenar los puntos por secuencia
routes = routes.sort_values(by="shape_pt_sequence")

# 2. Crear geometría LineString (usa lon, lat)
line = LineString(zip(routes["shape_pt_lon"], routes["shape_pt_lat"]))

# 3. Crear un GeoDataFrame con CRS WGS84 (EPSG:4326)
gdf = gpd.GeoDataFrame(
    {"shape_id": [routes["shape_id"].iloc[0]]},
    geometry=[line],
    crs="EPSG:4326"
)

# 4. Guardar a GeoJSON
gdf.to_file(f"route_line_{route}.geojson", driver="GeoJSON")

## Stops

In [48]:
path_stops = path_gtfs + "stops.txt"
stops = pd.read_csv(path_stops)

In [49]:
stops["route"] = stops["stop_id"].str.split("_").str[1]

In [55]:
stops["sequence"] = stops["stop_id"].str.split("_").str[-1]
stops["sequence"] = stops["sequence"].astype(int)

In [56]:
stops.head()

,stop_id,stop_name,stop_lon,stop_lat,route,sequence
0,st_r74_shape_74_0000,st_r74_shape_74_0000,-97.844810,22.209130,r74,0
1,st_r74_shape_74_0001,st_r74_shape_74_0001,-97.844291,22.210283,r74,1
2,st_r74_shape_74_0002,st_r74_shape_74_0002,-97.842709,22.211326,r74,2
3,st_r74_shape_74_0003,st_r74_shape_74_0003,-97.842802,22.211341,r74,3
4,st_r74_shape_74_0004,st_r74_shape_74_0004,-97.844393,22.210307,r74,4

In [57]:
stops = stops[stops["route"]== f"r{route}"]
stops.head()

,stop_id,stop_name,stop_lon,stop_lat,route,sequence
6586,st_r7_shape_7_0000,st_r7_shape_7_0000,-97.853200,22.217170,r7,0
6587,st_r7_shape_7_0001,st_r7_shape_7_0001,-97.852878,22.215928,r7,1
6588,st_r7_shape_7_0002,st_r7_shape_7_0002,-97.853767,22.214322,r7,2
6589,st_r7_shape_7_0003,st_r7_shape_7_0003,-97.854656,22.212716,r7,3
6590,st_r7_shape_7_0004,st_r7_shape_7_0004,-97.855696,22.212780,r7,4

In [58]:
stops.to_csv(f"./stops_route_{route}.csv", index=False)

## Sequence

In [39]:
path_stops_times = path_gtfs + "stop_times.txt"
stops_times = pd.read_csv(path_stops_times)

In [41]:
stops_times["route"] = stops_times["stop_id"].str.split("_").str[1]

In [44]:
stops_times = stops_times[stops_times["route"]== f"r{route}"]
stops_times.head(30)

,trip_id,timepoint,stop_id,stop_sequence,arrival_time,departure_time,route
172548,r7_trip_00_1,1,st_r7_shape_7_0000,1,05:59:48,06:00:00,r7
172549,r7_trip_00_1,1,st_r7_shape_7_0001,2,06:01:12,06:01:24,r7
172550,r7_trip_00_1,1,st_r7_shape_7_0002,3,06:02:36,06:02:48,r7
172551,r7_trip_00_1,1,st_r7_shape_7_0003,4,06:04:00,06:04:12,r7
172552,r7_trip_00_1,1,st_r7_shape_7_0004,5,06:05:24,06:05:36,r7
172553,r7_trip_00_1,1,st_r7_shape_7_0005,6,06:06:48,06:07:00,r7
172554,r7_trip_00_1,1,st_r7_shape_7_0006,7,06:08:12,06:08:24,r7
172555,r7_trip_00_1,1,st_r7_shape_7_0007,8,06:09:36,06:09:48,r7
172556,r7_trip_00_1,1,st_r7_shape_7_0008,9,06:11:00,06:11:12,r7
172557,r7_trip_00_1,1,st_r7_shape_7_0009,10,06:12:24,06:12:36,r7
172558,r7_trip_00_1,1,st_r7_shape_7_0010,11,06:13:48,06:14:00,r7
172559,r7_trip_00_1,1,st_r7_shape_7_0011,12,06:15:12,06:15:24,r7
172560,r7_trip_00_1,1,st_r7_shape_7_0012,13,06:16:36,06:16:48,r7
172561,r7_trip_00_1,1,st_r7_shape_7_0013,14,06:18:00,06:18:12,r7
172562,r7_trip_00_1,1,st_r7_shape_7_0014,15,06:19:24,06:19:36,r7
172563,r7_trip_00_1,1,st_r7_shape_7_0015,16,06:20:48,06:21:00,r7
172564,r7_trip_00_1,1,st_r7_shape_7_0016,17,06:22:12,06:22:24,r7
172565,r7_trip_00_1,1,st_r7_shape_7_0017,18,06:23:36,06:23:48,r7
172566,r7_trip_00_1,1,st_r7_shape_7_0018,19,06:25:00,06:25:12,r7
172567,r7_trip_00_1,1,st_r7_shape_7_0019,20,06:26:24,06:26:36,r7
172568,r7_trip_00_1,1,st_r7_shape_7_0020,21,06:27:48,06:28:00,r7
172569,r7_trip_00_1,1,st_r7_shape_7_0021,22,06:29:12,06:29:24,r7
172570,r7_trip_00_1,1,st_r7_shape_7_0022,23,06:30:36,06:30:48,r7
172571,r7_trip_00_1,1,st_r7_shape_7_0023,24,06:32:00,06:32:12,r7
172572,r7_trip_00_1,1,st_r7_shape_7_0024,25,06:33:24,06:33:36,r7
172573,r7_trip_00_1,1,st_r7_shape_7_0025,26,06:34:48,06:35:00,r7
172574,r7_trip_00_1,1,st_r7_shape_7_0026,27,06:36:12,06:36:24,r7
172575,r7_trip_00_1,1,st_r7_shape_7_0027,28,06:37:36,06:37:48,r7
172576,r7_trip_00_1,1,st_r7_shape_7_0028,29,06:39:00,06:39:12,r7
172577,r7_trip_00_1,1,st_r7_shape_7_0029,30,06:40:24,06:40:36,r7